### ISSUE TITLE
Respecting LSP hover ranges

### ISSUE THREAD

**Issue by efritz** [sourcegraph/codeintellify#224]
lsif-server returns ranges alongside hover text, but these are not used to adjust the highlighted token, which can appear incorrect due to the current heuristic scan.

```json
{
  "hover": {
    "markdown": {
      "text": "```go\npackage \"golang.org/x/tools/go/ast/astutil\"\n```
\n\n---\n\nPackage astutil contains common utilities for working with the Go AST.”
    },
    “range”: {
      “start”: {
        “line”: 12,
        “character”: 2
      },
      “end”: {
        “line”: 12,
        “character”: 35
      }
    }
  }
}
```

This is particular noticeable with go import paths, which should highlight the entire string content, not just the first ident-like token:

<img width="209" alt="Screen Shot 2020-02-27 at 10 06 29 AM" src="https://user-images.githubusercontent.com/103087/75464691-2d903200-594d-11ea-84df-60f60a27534e.png">

**Comment by efritz** [comment]
cc @felixfbecker

**Comment by felixfbecker** [comment]
Yeah, we currently ignore the returned hover range. The reason is that we highlight by changing the tokens background color, which means we change the background color of the closest `span`. This does the right thing in the majority of the cases. We can't color individual character ranges (unless we changed our approach completely and e.g. drew a semi-transparent span over the characters, but that is way more complex and looks different).

What we could do is color all spans that overlap with the range (but it's a little bit more complex).
